version: "3.7"
services:
  database:
    image: postgres
    container_name: agenda_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=agenda_base
    volumes:
      - pgdata:/data/postgres

  app:
    build: . # Especifica o diretório que será buildado para dentro do docker
    container_name: agenda-back # Especifica o nome do container que deverá ser criado
    ports:
      - 3333:3333 #configura a porta que será executada no docker quando for chamada na máquina host
    volumes:
      - .:/usr/app #copia os arquivos do diretório base ('.') para o diretório WORKDIR do dockerfile ('/usr/app')
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
